# Generated by Django 5.0.3 on 2024-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vname', models.CharField(max_length=100)),
                ('Vaddress', models.CharField(max_length=100)),
                ('Vmandal', models.CharField(max_length=100)),
                ('Vpostnumber', models.IntegerField()),
            ],
        ),
    ]
